// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DealNotice.proto

package com.artisankid.elementwar.ewmessagemodel;

public final class DealNoticeOuterClass {
  private DealNoticeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DealNoticeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DealNotice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double send_time = 2;</code>
     */
    double getSendTime();

    /**
     * <pre>
     *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double expired_time = 3;</code>
     */
    double getExpiredTime();

    /**
     * <pre>
     *是否需要响应
     * </pre>
     *
     * <code>bool needResponse = 4;</code>
     */
    boolean getNeedResponse();

    /**
     * <pre>
     *接收者ID
     * </pre>
     *
     * <code>string receiver_id = 20;</code>
     */
    java.lang.String getReceiverId();
    /**
     * <pre>
     *接收者ID
     * </pre>
     *
     * <code>string receiver_id = 20;</code>
     */
    com.google.protobuf.ByteString
        getReceiverIdBytes();

    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    java.util.List<java.lang.String>
        getCardIdsList();
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    int getCardIdsCount();
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    java.lang.String getCardIds(int index);
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    com.google.protobuf.ByteString
        getCardIdsBytes(int index);
  }
  /**
   * <pre>
   *发牌通知
   * </pre>
   *
   * Protobuf type {@code DealNotice}
   */
  public  static final class DealNotice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DealNotice)
      DealNoticeOrBuilder {
    // Use DealNotice.newBuilder() to construct.
    private DealNotice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DealNotice() {
      messageId_ = "";
      sendTime_ = 0D;
      expiredTime_ = 0D;
      needResponse_ = false;
      receiverId_ = "";
      cardIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DealNotice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 17: {

              sendTime_ = input.readDouble();
              break;
            }
            case 25: {

              expiredTime_ = input.readDouble();
              break;
            }
            case 32: {

              needResponse_ = input.readBool();
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverId_ = s;
              break;
            }
            case 242: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                cardIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              cardIds_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          cardIds_ = cardIds_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.internal_static_DealNotice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.internal_static_DealNotice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.class, com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEND_TIME_FIELD_NUMBER = 2;
    private double sendTime_;
    /**
     * <pre>
     *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double send_time = 2;</code>
     */
    public double getSendTime() {
      return sendTime_;
    }

    public static final int EXPIRED_TIME_FIELD_NUMBER = 3;
    private double expiredTime_;
    /**
     * <pre>
     *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double expired_time = 3;</code>
     */
    public double getExpiredTime() {
      return expiredTime_;
    }

    public static final int NEEDRESPONSE_FIELD_NUMBER = 4;
    private boolean needResponse_;
    /**
     * <pre>
     *是否需要响应
     * </pre>
     *
     * <code>bool needResponse = 4;</code>
     */
    public boolean getNeedResponse() {
      return needResponse_;
    }

    public static final int RECEIVER_ID_FIELD_NUMBER = 20;
    private volatile java.lang.Object receiverId_;
    /**
     * <pre>
     *接收者ID
     * </pre>
     *
     * <code>string receiver_id = 20;</code>
     */
    public java.lang.String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者ID
     * </pre>
     *
     * <code>string receiver_id = 20;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARD_IDS_FIELD_NUMBER = 30;
    private com.google.protobuf.LazyStringList cardIds_;
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCardIdsList() {
      return cardIds_;
    }
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    public int getCardIdsCount() {
      return cardIds_.size();
    }
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    public java.lang.String getCardIds(int index) {
      return cardIds_.get(index);
    }
    /**
     * <pre>
     *卡牌ID
     * </pre>
     *
     * <code>repeated string card_ids = 30;</code>
     */
    public com.google.protobuf.ByteString
        getCardIdsBytes(int index) {
      return cardIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (sendTime_ != 0D) {
        output.writeDouble(2, sendTime_);
      }
      if (expiredTime_ != 0D) {
        output.writeDouble(3, expiredTime_);
      }
      if (needResponse_ != false) {
        output.writeBool(4, needResponse_);
      }
      if (!getReceiverIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, receiverId_);
      }
      for (int i = 0; i < cardIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 30, cardIds_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (sendTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, sendTime_);
      }
      if (expiredTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, expiredTime_);
      }
      if (needResponse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, needResponse_);
      }
      if (!getReceiverIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, receiverId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cardIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(cardIds_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getCardIdsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice)) {
        return super.equals(obj);
      }
      com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice other = (com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && (
          java.lang.Double.doubleToLongBits(getSendTime())
          == java.lang.Double.doubleToLongBits(
              other.getSendTime()));
      result = result && (
          java.lang.Double.doubleToLongBits(getExpiredTime())
          == java.lang.Double.doubleToLongBits(
              other.getExpiredTime()));
      result = result && (getNeedResponse()
          == other.getNeedResponse());
      result = result && getReceiverId()
          .equals(other.getReceiverId());
      result = result && getCardIdsList()
          .equals(other.getCardIdsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSendTime()));
      hash = (37 * hash) + EXPIRED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getExpiredTime()));
      hash = (37 * hash) + NEEDRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedResponse());
      hash = (37 * hash) + RECEIVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverId().hashCode();
      if (getCardIdsCount() > 0) {
        hash = (37 * hash) + CARD_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getCardIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *发牌通知
     * </pre>
     *
     * Protobuf type {@code DealNotice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DealNotice)
        com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNoticeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.internal_static_DealNotice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.internal_static_DealNotice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.class, com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.Builder.class);
      }

      // Construct using com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";

        sendTime_ = 0D;

        expiredTime_ = 0D;

        needResponse_ = false;

        receiverId_ = "";

        cardIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.internal_static_DealNotice_descriptor;
      }

      public com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice getDefaultInstanceForType() {
        return com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.getDefaultInstance();
      }

      public com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice build() {
        com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice buildPartial() {
        com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice result = new com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.messageId_ = messageId_;
        result.sendTime_ = sendTime_;
        result.expiredTime_ = expiredTime_;
        result.needResponse_ = needResponse_;
        result.receiverId_ = receiverId_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          cardIds_ = cardIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.cardIds_ = cardIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice) {
          return mergeFrom((com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice other) {
        if (other == com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.getSendTime() != 0D) {
          setSendTime(other.getSendTime());
        }
        if (other.getExpiredTime() != 0D) {
          setExpiredTime(other.getExpiredTime());
        }
        if (other.getNeedResponse() != false) {
          setNeedResponse(other.getNeedResponse());
        }
        if (!other.getReceiverId().isEmpty()) {
          receiverId_ = other.receiverId_;
          onChanged();
        }
        if (!other.cardIds_.isEmpty()) {
          if (cardIds_.isEmpty()) {
            cardIds_ = other.cardIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureCardIdsIsMutable();
            cardIds_.addAll(other.cardIds_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private double sendTime_ ;
      /**
       * <pre>
       *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double send_time = 2;</code>
       */
      public double getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double send_time = 2;</code>
       */
      public Builder setSendTime(double value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double send_time = 2;</code>
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0D;
        onChanged();
        return this;
      }

      private double expiredTime_ ;
      /**
       * <pre>
       *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double expired_time = 3;</code>
       */
      public double getExpiredTime() {
        return expiredTime_;
      }
      /**
       * <pre>
       *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double expired_time = 3;</code>
       */
      public Builder setExpiredTime(double value) {
        
        expiredTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double expired_time = 3;</code>
       */
      public Builder clearExpiredTime() {
        
        expiredTime_ = 0D;
        onChanged();
        return this;
      }

      private boolean needResponse_ ;
      /**
       * <pre>
       *是否需要响应
       * </pre>
       *
       * <code>bool needResponse = 4;</code>
       */
      public boolean getNeedResponse() {
        return needResponse_;
      }
      /**
       * <pre>
       *是否需要响应
       * </pre>
       *
       * <code>bool needResponse = 4;</code>
       */
      public Builder setNeedResponse(boolean value) {
        
        needResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否需要响应
       * </pre>
       *
       * <code>bool needResponse = 4;</code>
       */
      public Builder clearNeedResponse() {
        
        needResponse_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object receiverId_ = "";
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>string receiver_id = 20;</code>
       */
      public java.lang.String getReceiverId() {
        java.lang.Object ref = receiverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>string receiver_id = 20;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverIdBytes() {
        java.lang.Object ref = receiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>string receiver_id = 20;</code>
       */
      public Builder setReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>string receiver_id = 20;</code>
       */
      public Builder clearReceiverId() {
        
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>string receiver_id = 20;</code>
       */
      public Builder setReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList cardIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCardIdsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          cardIds_ = new com.google.protobuf.LazyStringArrayList(cardIds_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCardIdsList() {
        return cardIds_.getUnmodifiableView();
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public int getCardIdsCount() {
        return cardIds_.size();
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public java.lang.String getCardIds(int index) {
        return cardIds_.get(index);
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public com.google.protobuf.ByteString
          getCardIdsBytes(int index) {
        return cardIds_.getByteString(index);
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public Builder setCardIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCardIdsIsMutable();
        cardIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public Builder addCardIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCardIdsIsMutable();
        cardIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public Builder addAllCardIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureCardIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cardIds_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public Builder clearCardIds() {
        cardIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卡牌ID
       * </pre>
       *
       * <code>repeated string card_ids = 30;</code>
       */
      public Builder addCardIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCardIdsIsMutable();
        cardIds_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DealNotice)
    }

    // @@protoc_insertion_point(class_scope:DealNotice)
    private static final com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice();
    }

    public static com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DealNotice>
        PARSER = new com.google.protobuf.AbstractParser<DealNotice>() {
      public DealNotice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DealNotice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DealNotice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DealNotice> getParserForType() {
      return PARSER;
    }

    public com.artisankid.elementwar.ewmessagemodel.DealNoticeOuterClass.DealNotice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DealNotice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DealNotice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DealNotice.proto\"\206\001\n\nDealNotice\022\022\n\nmes" +
      "sage_id\030\001 \001(\t\022\021\n\tsend_time\030\002 \001(\001\022\024\n\014expi" +
      "red_time\030\003 \001(\001\022\024\n\014needResponse\030\004 \001(\010\022\023\n\013" +
      "receiver_id\030\024 \001(\t\022\020\n\010card_ids\030\036 \003(\tB*\n(c" +
      "om.artisankid.elementwar.ewmessagemodelb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DealNotice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DealNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DealNotice_descriptor,
        new java.lang.String[] { "MessageId", "SendTime", "ExpiredTime", "NeedResponse", "ReceiverId", "CardIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
