// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InviteReplyNotice.proto

package com.artisankid.elementwar.ewmessagemodel;

public final class InviteReplyNoticeOuterClass {
  private InviteReplyNoticeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InviteReplyNoticeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InviteReplyNotice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double send_time = 2;</code>
     */
    double getSendTime();

    /**
     * <pre>
     *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double expired_time = 3;</code>
     */
    double getExpiredTime();

    /**
     * <pre>
     *回复者ID
     * </pre>
     *
     * <code>string sender_id = 20;</code>
     */
    java.lang.String getSenderId();
    /**
     * <pre>
     *回复者ID
     * </pre>
     *
     * <code>string sender_id = 20;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     *回复者名
     * </pre>
     *
     * <code>string sender_name = 21;</code>
     */
    java.lang.String getSenderName();
    /**
     * <pre>
     *回复者名
     * </pre>
     *
     * <code>string sender_name = 21;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <pre>
     *回复者头像
     * </pre>
     *
     * <code>string sender_portrait_url = 22;</code>
     */
    java.lang.String getSenderPortraitUrl();
    /**
     * <pre>
     *回复者头像
     * </pre>
     *
     * <code>string sender_portrait_url = 22;</code>
     */
    com.google.protobuf.ByteString
        getSenderPortraitUrlBytes();

    /**
     * <pre>
     *是否同意
     * </pre>
     *
     * <code>bool isAgree = 31;</code>
     */
    boolean getIsAgree();

    /**
     * <pre>
     *提示
     * </pre>
     *
     * <code>string alert = 32;</code>
     */
    java.lang.String getAlert();
    /**
     * <pre>
     *提示
     * </pre>
     *
     * <code>string alert = 32;</code>
     */
    com.google.protobuf.ByteString
        getAlertBytes();
  }
  /**
   * <pre>
   *邀请回复通知
   * </pre>
   *
   * Protobuf type {@code InviteReplyNotice}
   */
  public  static final class InviteReplyNotice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InviteReplyNotice)
      InviteReplyNoticeOrBuilder {
    // Use InviteReplyNotice.newBuilder() to construct.
    private InviteReplyNotice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InviteReplyNotice() {
      messageId_ = "";
      sendTime_ = 0D;
      expiredTime_ = 0D;
      senderId_ = "";
      senderName_ = "";
      senderPortraitUrl_ = "";
      isAgree_ = false;
      alert_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InviteReplyNotice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 17: {

              sendTime_ = input.readDouble();
              break;
            }
            case 25: {

              expiredTime_ = input.readDouble();
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              senderId_ = s;
              break;
            }
            case 170: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 178: {
              java.lang.String s = input.readStringRequireUtf8();

              senderPortraitUrl_ = s;
              break;
            }
            case 248: {

              isAgree_ = input.readBool();
              break;
            }
            case 258: {
              java.lang.String s = input.readStringRequireUtf8();

              alert_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.internal_static_InviteReplyNotice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.internal_static_InviteReplyNotice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.class, com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.Builder.class);
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEND_TIME_FIELD_NUMBER = 2;
    private double sendTime_;
    /**
     * <pre>
     *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double send_time = 2;</code>
     */
    public double getSendTime() {
      return sendTime_;
    }

    public static final int EXPIRED_TIME_FIELD_NUMBER = 3;
    private double expiredTime_;
    /**
     * <pre>
     *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
     * </pre>
     *
     * <code>double expired_time = 3;</code>
     */
    public double getExpiredTime() {
      return expiredTime_;
    }

    public static final int SENDER_ID_FIELD_NUMBER = 20;
    private volatile java.lang.Object senderId_;
    /**
     * <pre>
     *回复者ID
     * </pre>
     *
     * <code>string sender_id = 20;</code>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *回复者ID
     * </pre>
     *
     * <code>string sender_id = 20;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_NAME_FIELD_NUMBER = 21;
    private volatile java.lang.Object senderName_;
    /**
     * <pre>
     *回复者名
     * </pre>
     *
     * <code>string sender_name = 21;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *回复者名
     * </pre>
     *
     * <code>string sender_name = 21;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_PORTRAIT_URL_FIELD_NUMBER = 22;
    private volatile java.lang.Object senderPortraitUrl_;
    /**
     * <pre>
     *回复者头像
     * </pre>
     *
     * <code>string sender_portrait_url = 22;</code>
     */
    public java.lang.String getSenderPortraitUrl() {
      java.lang.Object ref = senderPortraitUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderPortraitUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *回复者头像
     * </pre>
     *
     * <code>string sender_portrait_url = 22;</code>
     */
    public com.google.protobuf.ByteString
        getSenderPortraitUrlBytes() {
      java.lang.Object ref = senderPortraitUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderPortraitUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISAGREE_FIELD_NUMBER = 31;
    private boolean isAgree_;
    /**
     * <pre>
     *是否同意
     * </pre>
     *
     * <code>bool isAgree = 31;</code>
     */
    public boolean getIsAgree() {
      return isAgree_;
    }

    public static final int ALERT_FIELD_NUMBER = 32;
    private volatile java.lang.Object alert_;
    /**
     * <pre>
     *提示
     * </pre>
     *
     * <code>string alert = 32;</code>
     */
    public java.lang.String getAlert() {
      java.lang.Object ref = alert_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alert_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提示
     * </pre>
     *
     * <code>string alert = 32;</code>
     */
    public com.google.protobuf.ByteString
        getAlertBytes() {
      java.lang.Object ref = alert_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alert_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (sendTime_ != 0D) {
        output.writeDouble(2, sendTime_);
      }
      if (expiredTime_ != 0D) {
        output.writeDouble(3, expiredTime_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, senderId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 21, senderName_);
      }
      if (!getSenderPortraitUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, senderPortraitUrl_);
      }
      if (isAgree_ != false) {
        output.writeBool(31, isAgree_);
      }
      if (!getAlertBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 32, alert_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (sendTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, sendTime_);
      }
      if (expiredTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, expiredTime_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, senderId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, senderName_);
      }
      if (!getSenderPortraitUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, senderPortraitUrl_);
      }
      if (isAgree_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(31, isAgree_);
      }
      if (!getAlertBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(32, alert_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice)) {
        return super.equals(obj);
      }
      com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice other = (com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && (
          java.lang.Double.doubleToLongBits(getSendTime())
          == java.lang.Double.doubleToLongBits(
              other.getSendTime()));
      result = result && (
          java.lang.Double.doubleToLongBits(getExpiredTime())
          == java.lang.Double.doubleToLongBits(
              other.getExpiredTime()));
      result = result && getSenderId()
          .equals(other.getSenderId());
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getSenderPortraitUrl()
          .equals(other.getSenderPortraitUrl());
      result = result && (getIsAgree()
          == other.getIsAgree());
      result = result && getAlert()
          .equals(other.getAlert());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSendTime()));
      hash = (37 * hash) + EXPIRED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getExpiredTime()));
      hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (37 * hash) + SENDER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + SENDER_PORTRAIT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPortraitUrl().hashCode();
      hash = (37 * hash) + ISAGREE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAgree());
      hash = (37 * hash) + ALERT_FIELD_NUMBER;
      hash = (53 * hash) + getAlert().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *邀请回复通知
     * </pre>
     *
     * Protobuf type {@code InviteReplyNotice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InviteReplyNotice)
        com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNoticeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.internal_static_InviteReplyNotice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.internal_static_InviteReplyNotice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.class, com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.Builder.class);
      }

      // Construct using com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";

        sendTime_ = 0D;

        expiredTime_ = 0D;

        senderId_ = "";

        senderName_ = "";

        senderPortraitUrl_ = "";

        isAgree_ = false;

        alert_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.internal_static_InviteReplyNotice_descriptor;
      }

      public com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice getDefaultInstanceForType() {
        return com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.getDefaultInstance();
      }

      public com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice build() {
        com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice buildPartial() {
        com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice result = new com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice(this);
        result.messageId_ = messageId_;
        result.sendTime_ = sendTime_;
        result.expiredTime_ = expiredTime_;
        result.senderId_ = senderId_;
        result.senderName_ = senderName_;
        result.senderPortraitUrl_ = senderPortraitUrl_;
        result.isAgree_ = isAgree_;
        result.alert_ = alert_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice) {
          return mergeFrom((com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice other) {
        if (other == com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.getSendTime() != 0D) {
          setSendTime(other.getSendTime());
        }
        if (other.getExpiredTime() != 0D) {
          setExpiredTime(other.getExpiredTime());
        }
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          onChanged();
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getSenderPortraitUrl().isEmpty()) {
          senderPortraitUrl_ = other.senderPortraitUrl_;
          onChanged();
        }
        if (other.getIsAgree() != false) {
          setIsAgree(other.getIsAgree());
        }
        if (!other.getAlert().isEmpty()) {
          alert_ = other.alert_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>string message_id = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private double sendTime_ ;
      /**
       * <pre>
       *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double send_time = 2;</code>
       */
      public double getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double send_time = 2;</code>
       */
      public Builder setSendTime(double value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double send_time = 2;</code>
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0D;
        onChanged();
        return this;
      }

      private double expiredTime_ ;
      /**
       * <pre>
       *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double expired_time = 3;</code>
       */
      public double getExpiredTime() {
        return expiredTime_;
      }
      /**
       * <pre>
       *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double expired_time = 3;</code>
       */
      public Builder setExpiredTime(double value) {
        
        expiredTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *过期时间戳，因为时间戳处在1482934107这种量级，超过2^28，需要fixed32这种高效率编码类型
       * </pre>
       *
       * <code>double expired_time = 3;</code>
       */
      public Builder clearExpiredTime() {
        
        expiredTime_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object senderId_ = "";
      /**
       * <pre>
       *回复者ID
       * </pre>
       *
       * <code>string sender_id = 20;</code>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *回复者ID
       * </pre>
       *
       * <code>string sender_id = 20;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *回复者ID
       * </pre>
       *
       * <code>string sender_id = 20;</code>
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *回复者ID
       * </pre>
       *
       * <code>string sender_id = 20;</code>
       */
      public Builder clearSenderId() {
        
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *回复者ID
       * </pre>
       *
       * <code>string sender_id = 20;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <pre>
       *回复者名
       * </pre>
       *
       * <code>string sender_name = 21;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *回复者名
       * </pre>
       *
       * <code>string sender_name = 21;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *回复者名
       * </pre>
       *
       * <code>string sender_name = 21;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *回复者名
       * </pre>
       *
       * <code>string sender_name = 21;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *回复者名
       * </pre>
       *
       * <code>string sender_name = 21;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderPortraitUrl_ = "";
      /**
       * <pre>
       *回复者头像
       * </pre>
       *
       * <code>string sender_portrait_url = 22;</code>
       */
      public java.lang.String getSenderPortraitUrl() {
        java.lang.Object ref = senderPortraitUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderPortraitUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *回复者头像
       * </pre>
       *
       * <code>string sender_portrait_url = 22;</code>
       */
      public com.google.protobuf.ByteString
          getSenderPortraitUrlBytes() {
        java.lang.Object ref = senderPortraitUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderPortraitUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *回复者头像
       * </pre>
       *
       * <code>string sender_portrait_url = 22;</code>
       */
      public Builder setSenderPortraitUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderPortraitUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *回复者头像
       * </pre>
       *
       * <code>string sender_portrait_url = 22;</code>
       */
      public Builder clearSenderPortraitUrl() {
        
        senderPortraitUrl_ = getDefaultInstance().getSenderPortraitUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *回复者头像
       * </pre>
       *
       * <code>string sender_portrait_url = 22;</code>
       */
      public Builder setSenderPortraitUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderPortraitUrl_ = value;
        onChanged();
        return this;
      }

      private boolean isAgree_ ;
      /**
       * <pre>
       *是否同意
       * </pre>
       *
       * <code>bool isAgree = 31;</code>
       */
      public boolean getIsAgree() {
        return isAgree_;
      }
      /**
       * <pre>
       *是否同意
       * </pre>
       *
       * <code>bool isAgree = 31;</code>
       */
      public Builder setIsAgree(boolean value) {
        
        isAgree_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否同意
       * </pre>
       *
       * <code>bool isAgree = 31;</code>
       */
      public Builder clearIsAgree() {
        
        isAgree_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object alert_ = "";
      /**
       * <pre>
       *提示
       * </pre>
       *
       * <code>string alert = 32;</code>
       */
      public java.lang.String getAlert() {
        java.lang.Object ref = alert_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alert_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *提示
       * </pre>
       *
       * <code>string alert = 32;</code>
       */
      public com.google.protobuf.ByteString
          getAlertBytes() {
        java.lang.Object ref = alert_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alert_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提示
       * </pre>
       *
       * <code>string alert = 32;</code>
       */
      public Builder setAlert(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        alert_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示
       * </pre>
       *
       * <code>string alert = 32;</code>
       */
      public Builder clearAlert() {
        
        alert_ = getDefaultInstance().getAlert();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示
       * </pre>
       *
       * <code>string alert = 32;</code>
       */
      public Builder setAlertBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        alert_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:InviteReplyNotice)
    }

    // @@protoc_insertion_point(class_scope:InviteReplyNotice)
    private static final com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice();
    }

    public static com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InviteReplyNotice>
        PARSER = new com.google.protobuf.AbstractParser<InviteReplyNotice>() {
      public InviteReplyNotice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InviteReplyNotice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InviteReplyNotice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InviteReplyNotice> getParserForType() {
      return PARSER;
    }

    public com.artisankid.elementwar.ewmessagemodel.InviteReplyNoticeOuterClass.InviteReplyNotice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InviteReplyNotice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InviteReplyNotice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027InviteReplyNotice.proto\"\265\001\n\021InviteRepl" +
      "yNotice\022\022\n\nmessage_id\030\001 \001(\t\022\021\n\tsend_time" +
      "\030\002 \001(\001\022\024\n\014expired_time\030\003 \001(\001\022\021\n\tsender_i" +
      "d\030\024 \001(\t\022\023\n\013sender_name\030\025 \001(\t\022\033\n\023sender_p" +
      "ortrait_url\030\026 \001(\t\022\017\n\007isAgree\030\037 \001(\010\022\r\n\005al" +
      "ert\030  \001(\tB*\n(com.artisankid.elementwar.e" +
      "wmessagemodelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InviteReplyNotice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InviteReplyNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InviteReplyNotice_descriptor,
        new java.lang.String[] { "MessageId", "SendTime", "ExpiredTime", "SenderId", "SenderName", "SenderPortraitUrl", "IsAgree", "Alert", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
